<a href="https://colab.research.google.com/github/alejandrolq/StaticalLearningII-Practicas/blob/main/Ejercicio_XOR_Composicion_Perceptrones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nombre: José Alejandro López Quel**

**Carné: 21001127**

**Statical Learning II**

**Sección U**

**Ejercicio: XOR con composición y perceptrones**

In [99]:
import numpy as np

## Perceptrón NOT

In [100]:
def not_function(X):
  parameters = [-1,1]
  X = np.append(X, np.ones((X.shape[0], 1)), axis = -1)
  result = np.matmul(X,parameters)  
  return result.reshape(len(result), 1)

In [101]:
X = np.array([[1], [0], [1]])

In [102]:
not_function(X)

array([[0.],
       [1.],
       [0.]])

## Perceptrón OR

In [103]:
def or_function(X1, X2=[]):
  parameters = [1, 1, 0]
  if len(X2):
    X = np.append(X1, X2, axis = -1)
    X = np.append(X, np.ones((X.shape[0], 1)), axis = -1)
  else:
    X = np.append(X1, np.ones((X1.shape[0], 1)), axis = -1)
  result = np.matmul(X,parameters) > 0
  return result.reshape(len(result), 1).astype(int)

In [104]:
X1 = np.array([[1], [1], [0]])
X2 = np.array([[1], [0], [0]])

In [105]:
or_function(X1, X2)

array([[1],
       [1],
       [0]])

In [106]:
X = np.array([[1,1], [0,1], [0,0]])

In [107]:
or_function(X)

array([[1],
       [1],
       [0]])

## Perceptrón AND

In [108]:
def and_function(X1, X2=[]):
  parameters = [1, 1, -1]
  if len(X2):
    X = np.append(X1, X2, axis = -1)
    X = np.append(X, np.ones((X.shape[0], 1)), axis = -1)
  else:
    X = np.append(X1, np.ones((X1.shape[0], 1)), axis = -1)
  result = np.matmul(X,parameters) > 0
  return result.reshape(len(result), 1).astype(int)

In [109]:
X1 = np.array([[1], [1], [0]])
X2 = np.array([[1], [0], [0]])

In [110]:
and_function(X1, X2)

array([[1],
       [0],
       [0]])

In [111]:
X = np.array([[1,1], [0,1], [0,0]])

In [112]:
and_function(X)

array([[1],
       [0],
       [0]])

## Perceptrón XOR

In [113]:
def xor_function(X):  
  X1_temp = not_function(and_function(X))
  X2_temp = or_function(X)
  result = and_function(X1_temp, X2_temp)
  return result.reshape(len(result), 1)

In [114]:
X = np.array([[1,1], [0,1], [0,0], [1,0]])

In [115]:
xor_function(X)

array([[0],
       [1],
       [0],
       [1]])

## Conclusiones

- Se obtiene que la función XOR definida es una muestra de cómo la composición de funciones puede generar espacios latentes en donde los datos de entrada son separables linealmente, lo cual a su vez es la base para el aprendizaje profundo.